name: Generate Badges

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Badges
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Create the badges directory if it doesn't exist
            const badgesDir = path.join(process.env.GITHUB_WORKSPACE, 'badges');
            if (!fs.existsSync(badgesDir)) {
              fs.mkdirSync(badgesDir);
            }

            // Create the badge SVG
            const badgeSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="104" height="20">
              <linearGradient id="b" x2="0" y2="100%">
                <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
                <stop offset="1" stop-opacity=".1"/>
              </linearGradient>
              <mask id="a">
                <rect width="104" height="20" rx="3" fill="#fff"/>
              </mask>
              <g mask="url(#a)">
                <path fill="#555" d="M0 0h54v20H0z"/>
                <path fill="#4c1" d="M54 0h50v20H54z"/>
                <path fill="url(#b)" d="M0 0h104v20H0z"/>
              </g>
              <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
                <text x="27" y="15" fill="#010101" fill-opacity=".3">CI/CD</text>
                <text x="27" y="14">CI/CD</text>
                <text x="78" y="15" fill="#010101" fill-opacity=".3">passing</text>
                <text x="78" y="14">passing</text>
              </g>
            </svg>`;

            fs.writeFileSync(path.join(badgesDir, 'badge.svg'), badgeSvg);

      - name: Commit and push badges
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add badges/
          git commit -m "Update badges" || echo "No changes to commit"
          git push
